[package]
name = "scupre"
version = "0.2.0"
entrypoint = "lib.typ"
authors = ["OrangeX4", "Andreas Kröpelin", "ntjess", "Enivex", "Pol Dellaiera", "pride7", "Coekjan"]
license = "MIT"
description = "A powerful package for creating presentation slides in Typst."
repository = "https://github.com/touying-typ/touying"
keywords = ["presentation", "slides", "lecture", "touying"]
categories = ["presentation"]
exclude = ["examples"]
compiler = "0.11.0"


[template]
path = "template"
entrypoint = "main.typ"
thumbnail = "thumbnail.png"